version: "3.7"
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=default_password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  postgres-test-db:
    container_name: postgres-test-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=default_password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5430:5432"
    command: ["postgres", "-c", "log_statement=all"]
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
