@localhost = http://localhost:8888

### ---------- LOCALHOST ENDPOINTS ---------- ###

### Get all users ###

GET {{localhost}}/users
Authorization: Basic test:testpw

### Get user by id ###

GET {{localhost}}/users/0bd80bb2-5b2a-4edc-8830-53ce22d
Authorization: Basic test:testpw

### Create user ###
POST {{localhost}}/users
Authorization: Basic test:testpw
Content-Type: application/json

{
    "name": "test 3",
    "email": "test@mail.com"
}

### Update user by id ###
PUT {{localhost}}/users/339ca0cb-60f0-4793-a1bc-38e2d5e76703
Authorization: Basic test:testpw
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.pl"
}

### Delete user by id ###
DELETE {{localhost}}/users/6315fed4-75fa-43b6-8cc6-b47fdf02a3b4
Authorization: Basic test:testpw
Content-Type: application/json
